language: node_js
before_deploy:
- zip -r latest * -x bower_components/\* -x node_modules/\* -x coverage/\*
- mkdir -p cd_upload
- mv latest.zip cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: &1
    secure: CVkV0GyaycFq66EdCI/AzwZkj1FIibyNEXuKRhyM5IQLgpkripd/84FDzSc0+5TqQcdq6Ab7k5axEg0Iv7+9QhlfOch9phSBry3/sOHay9uZxilQ50/d5NdNDO68vKjVCl31QtWdqLicok08UiEgXEl7SZOP59LwqvsChBkN0U1HwpdCsB1IoJ0RbzM3NZqKXkvd/6SVKMaFzkKbBQ4CPUBAtUr4IdOD9INITLE51w2DNBAqiBE1EoAdVaUqruZikSVKydrBUHav9t4xc16wKBvAOrvU3GeMBn1Teo0xgoA8v5S0+vwjgVvMWLycH0plGiIElRlJrsT6vgIFf+P1IaGSzOQkkUBO35tEmeBPd9TtfO+p/FAahdWWpJ8kd144beGzitBfDY8O/PG+UW+eH9xsKzjwRWAI3bsSzLRxZZKa2fyfTOJxIh4hjmKxVy9WmWPBrC/ECyTVt9+2YrduOAelZy2Myl8qHMQPx4NCWrrRfugYj6ZNcXty299vdTCO20/RbvKV9Ovx/0x4uWYgPBQQGStnXbEcOYiKbXCF8tSfIPDcLIGUY+BcHL8v0JlC7g4AdNDd8Ljk1Gpcbc4eRfwP+jj4lVdiyRgb5JDfPCC94AyAj/sRLb9phjsjTCoXQ6YRbgOLw+6g60HxXkeSLWSIgKV7ettcutteJe9bvHw=
  secret_access_key: &2
    secure: TLhAcg01kcbqcARTUSWPieue5h8gn3HZ5cNT1avrcDgfTGIt+cMDL/zzTP0ci/ZLdoBrXv5UCiVIm8mcyR1+vqVq3yBwqpaLlqu1x+hRqmWGQvhlN6S6lyheYwFyBh6i4KtReVuxN9ylOSQSttVppKl5ousNcoNevt5srZ4kY0QRJpgrUUfD0B2RCqoH6E8MnsX5WX6pPg5p0vtOrQSFQnlZcJ7SVL7fvKrsNNNnu1fwsRnhS11InnQAAxKGCCIpISg+vVLMOo8NNhryEt+TCFowltW30s6ogo1EM3fAX7KRpjy0JU7rbuPBACbughmuOhWrx3BB9PKxNKqUjMx5waPVDBl1MdWGJhnYVrvyRoI2DtLhtKx2PQEQJkHcaf+o98khyi+Vl9yg9xhlwXAPUyoIqcD0mCUJRIS+I1vuGduNfSp52EcxgEwqCHOMgqcf+jnbgsXpg95YZU4c1iYFyGfU1fvXJc94wHVYYp/zIVcciKjOI51Msg6hDuNuW2CDAtSz4cILdFJ09POIqDQXdk29uEpUgijrMZn0XvvZ3eyUq1/exx9ElbDyq0gpKdYd4I0VpjfFZ93+o1p0sOKzZcW5EwusNN+dpLjZ3CkORm1ptRIfwBKA9SnjcD8OcLUKyh+qrqZEsbP0dz7IZdCPnWSFO7/ACdKtF2M9GQLNGP0=
  bucket: quizit-resources
  skip_cleanup: true
  local_dir: cd_upload
  upload-dir: codedeploy
  on: &3
    repo: jose-zama/quizit
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: quizit-resources
  key: codedeploy/latest.zip
  bundle_type: zip
  application: quizit
  deployment_group: quizit
  on: *3
  wait-until-deployed: true
notifications:
  slack:
    secure: S/NPk/XAmlbX1pycm5mAdak/39IzgbxEMuIZisPfm8+064dlAy96Bbsp1RIq2ypZcNVxHPYrWFiGdAs2KEJa3VSeYKMw1tdCXAQTl0vPN8PweoR2yXHbLLzfLVIFUfoqQ7zQLF6Dtbw8Gsfjvk7qQ5ffk1QNuYezDz231m9+RXJlzZ5BRR/uoeEavJkZRejHX5p5xuKcZbrtWrIhsF0mSLOqA8mSlq5OrgR4mOc/gDHaS0mxZZlDDaJny2OgqrttdU5oQO/lQiLUFAQhBsIv4uEz/YPvuqW2cKPrhH0FtzcsD/0PSfytmfCv3JvkS6uiW+dtdT6KPb5AS530SWBvIr2Qhkqp3LMetZe/Tw3BW26vlKeUBGQo23iATeTy9BQ2Qk1V5OGamVKUvp8Sq5U7uy6LOsRz8G8eX0dWdH76QZkZd7uysuHytzGvxVdrRZwVrqTYqWK8W3atgBtyaCqBkRAeNkc075YiaShuHu+WVUAyQFPyRuRSdAI6tDNgISdtz/ZuPJnxyEdyXLObek4IDXdI1bYQPvcZy9Vc4iu4QbmF/1xsxLVAqXWl5es/Kl+tQPCrBKyckVHpU6tfGHAN4Ywj5wRxFPGnKEYWUzm2QBqYR/fN45RTOkSRqD/PbjVcMVmAAc/otGM85lBQ2n7fZ05Jz8k/ToMBlZFTi9UdnZI=
